export const pricingPlans = {
  monthly: [
    {
      name: "Free",
      description: "Access free courses and explore our learning platform",
      price: 0,
      billing: "Always free, no commitment",
      badge: "😍 No credit card",
      features: [
        "Access to free courses only",
        "Create learning profile",
        "Course discussions & community",
        "Mobile app access",
        "Basic course materials",
        "24/7 support",
      ],
    },
    {
      name: "Pro",
      description: "Full access to all courses and premium features",
      price: 24.99,
      billing: "billed annually",
      badge: "💪 Most popular",
      features: [
        "Access to all courses",
        "30-day money-back guarantee",
        "Private sessions with instructors",
        "Offline downloads",
        "Course completion certificates",
        "Priority support",
        "Ad-free experience",
        "Exclusive webinars",
      ],
    },
    {
      name: "Lifetime",
      description: "One-time payment for unlimited lifetime access",
      price: 399,
      billing: "One-time payment",
      badge: "🔥Best Value",
      features: [
        "Lifetime access to all courses",
        "All Pro features included",
        "Free Courseloom t-shirt",
        "Early access to new courses",
        "Lifetime updates",
        "Exclusive community access",
        "Personal learning advisor",
        "Custom learning paths",
      ],
    },
  ],
  yearly: [
    {
      name: "Free",
      description: "Access free courses and explore our learning platform",
      price: 0,
      billing: "Always free, no commitment",
      badge: "😍 No credit card",
      features: [
        "Access to free courses only",
        "Create learning profile",
        "Course discussions & community",
        "Mobile app access",
        "Basic course materials",
        "24/7 support",
      ],
    },
    {
      name: "Pro",
      description: "Full access to all courses and premium features",
      price: 20,
      billing: "billed annually",
      badge: "💪 Most popular",
      features: [
        "Access to all courses",
        "30-day money-back guarantee",
        "Private sessions with instructors",
        "Offline downloads",
        "Course completion certificates",
        "Priority support",
        "Ad-free experience",
        "Exclusive webinars",
      ],
    },
    {
      name: "Lifetime",
      description: "One-time payment for unlimited lifetime access",
      price: 399,
      billing: "One-time payment",
      badge: "🔥Best Value",
      features: [
        "Lifetime access to all courses",
        "All Pro features included",
        "Free Courseloom t-shirt",
        "Early access to new courses",
        "Lifetime updates",
        "Exclusive community access",
        "Personal learning advisor",
        "Custom learning paths",
      ],
    },
  ],
};
